### ISSUE TITLE
extensions.zotero.reopenPanesOnRestart not work

### ISSUE THREAD

**Issue by actforjason** [Dominic-DallOsto/Zotero-Dark-Theme#44]
function of reopenPanesOnRestart ：
https://forums.zotero.org/discussion/85083/hide-item-pane-toggle-forgotten-on-restart

**Comment by actforjason** [comment]
修改成这样，reopenPanesOnRestart就正常了
```CSS
#zotero-items-splitter {
    /*display: none;*/
    visibility: hidden;
}
```
